load("@rules_tla//tla:defs.bzl", "tla_check")
load(":storage_models.bzl", "STORAGE_MODELS")

package(default_visibility = ["//visibility:public"])

[
    tla_check(
        name = model + "_check",
        config = model + ".cfg",
        module = model + ".tla",
        tags = [
            "storage",
            "tla",
        ],
        timeout_seconds = 1800,
        tlc_args = [
            "-cleanup",
            "-workers",
            "auto",
        ],
    )
    for model in STORAGE_MODELS
]

test_suite(
    name = "storage_models",
    tests = [":" + model + "_check" for model in STORAGE_MODELS],
)
